# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 07e3d747806aa962116945b84482f9f0056f8e80

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

spring:
    mail:
        host: localhost
        port: 25
        user:
        password:
        protocol: smtp
        tls: false
        auth: false
        from: MicSearch@localhost

    messageSource:
        cacheSeconds: 1

authentication:
    xauth:
        secret: myXAuthSecret
        # Token is valid 30 minutes
        tokenValidityInSeconds: 1800

swagger:
    title: MicSearch API
    description: Microservice for Searching!
    termsOfServiceUrl: http://jhipster.github.io/
    contact: LeventOzk@garanti.com.tr
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
